services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: petronect
      POSTGRES_PASSWORD: 37LnopSdH35imauBaaT8kmRNzsFoOzQT
      POSTGRES_DB: petronect

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://petronet:37LnopSdH35imauBaaT8kmRNzsFoOzQT@dpg-cu3rleogph6c738gq4pg-a.oregon-postgres.render.com/petronect
      

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
